#define luaL_addgsub lua54_luaL_addgsub
#define luaL_addlstring lua54_luaL_addlstring
#define luaL_addstring lua54_luaL_addstring
#define luaL_addvalue lua54_luaL_addvalue
#define luaL_argerror lua54_luaL_argerror
#define luaL_buffinit lua54_luaL_buffinit
#define luaL_buffinitsize lua54_luaL_buffinitsize
#define luaL_callmeta lua54_luaL_callmeta
#define luaL_checkany lua54_luaL_checkany
#define luaL_checkinteger lua54_luaL_checkinteger
#define luaL_checklstring lua54_luaL_checklstring
#define luaL_checknumber lua54_luaL_checknumber
#define luaL_checkoption lua54_luaL_checkoption
#define luaL_checkstack lua54_luaL_checkstack
#define luaL_checktype lua54_luaL_checktype
#define luaL_checkudata lua54_luaL_checkudata
#define luaL_checkversion_ lua54_luaL_checkversion_
#define luaL_error lua54_luaL_error
#define luaL_execresult lua54_luaL_execresult
#define luaL_fileresult lua54_luaL_fileresult
#define luaL_getmetafield lua54_luaL_getmetafield
#define luaL_getsubtable lua54_luaL_getsubtable
#define luaL_gsub lua54_luaL_gsub
#define luaL_len lua54_luaL_len
#define luaL_loadbufferx lua54_luaL_loadbufferx
#define luaL_loadfilex lua54_luaL_loadfilex
#define luaL_loadstring lua54_luaL_loadstring
#define luaL_newmetatable lua54_luaL_newmetatable
#define luaL_newstate lua54_luaL_newstate
#define luaL_openselectedlibs lua54_openselectedlibs
#define luaL_optinteger lua54_luaL_optinteger
#define luaL_optlstring lua54_luaL_optlstring
#define luaL_optnumber lua54_luaL_optnumber
#define luaL_prepbuffsize lua54_luaL_prepbuffsize
#define luaL_pushresult lua54_luaL_pushresult
#define luaL_pushresultsize lua54_luaL_pushresultsize
#define luaL_ref lua54_luaL_ref
#define luaL_requiref lua54_luaL_requiref
#define luaL_setfuncs lua54_luaL_setfuncs
#define luaL_setmetatable lua54_luaL_setmetatable
#define luaL_testudata lua54_luaL_testudata
#define luaL_tolstring lua54_luaL_tolstring
#define luaL_traceback lua54_luaL_traceback
#define luaL_typeerror lua54_luaL_typeerror
#define luaL_unref lua54_luaL_unref
#define luaL_where lua54_luaL_where
#define luaL_openlibs lua54_luaL_openlibs
#define lua_absindex lua54_lua_absindex
#define lua_arith lua54_lua_arith
#define lua_atpanic lua54_lua_atpanic
#define lua_callk lua54_lua_callk
#define lua_checkstack lua54_lua_checkstack
#define lua_close lua54_lua_close
#define lua_closeslot lua54_lua_closeslot
#define lua_closethread lua54_lua_closethread
#define lua_compare lua54_lua_compare
#define lua_concat lua54_lua_concat
#define lua_copy lua54_lua_copy
#define lua_createtable lua54_lua_createtable
#define lua_dump lua54_lua_dump
#define lua_error lua54_lua_error
#define lua_gc lua54_lua_gc
#define lua_getallocf lua54_lua_getallocf
#define lua_getfield lua54_lua_getfield
#define lua_getglobal lua54_lua_getglobal
#define lua_gethook lua54_lua_gethook
#define lua_gethookcount lua54_lua_gethookcount
#define lua_gethookmask lua54_lua_gethookmask
#define lua_geti lua54_lua_geti
#define lua_getinfo lua54_lua_getinfo
#define lua_getiuservalue lua54_lua_getiuservalue
#define lua_getlocal lua54_lua_getlocal
#define lua_getmetatable lua54_lua_getmetatable
#define lua_getstack lua54_lua_getstack
#define lua_gettable lua54_lua_gettable
#define lua_gettop lua54_lua_gettop
#define lua_getupvalue lua54_lua_getupvalue
#define lua_iscfunction lua54_lua_iscfunction
#define lua_isinteger lua54_lua_isinteger
#define lua_isnumber lua54_lua_isnumber
#define lua_isstring lua54_lua_isstring
#define lua_isuserdata lua54_lua_isuserdata
#define lua_isyieldable lua54_lua_isyieldable
#define lua_len lua54_lua_len
#define lua_load lua54_lua_load
#define lua_newstate lua54_lua_newstate
#define lua_newthread lua54_lua_newthread
#define lua_newuserdatauv lua54_lua_newuserdatauv
#define lua_next lua54_lua_next
#define lua_pcallk lua54_lua_pcallk
#define lua_pushboolean lua54_lua_pushboolean
#define lua_pushcclosure lua54_lua_pushcclosure
#define lua_pushfstring lua54_lua_pushfstring
#define lua_pushinteger lua54_lua_pushinteger
#define lua_pushlightuserdata lua54_lua_pushlightuserdata
#define lua_pushlstring lua54_lua_pushlstring
#define lua_pushnil lua54_lua_pushnil
#define lua_pushnumber lua54_lua_pushnumber
#define lua_pushstring lua54_lua_pushstring
#define lua_pushthread lua54_lua_pushthread
#define lua_pushvalue lua54_lua_pushvalue
#define lua_pushvfstring lua54_lua_pushvfstring
#define lua_rawequal lua54_lua_rawequal
#define lua_rawget lua54_lua_rawget
#define lua_rawgeti lua54_lua_rawgeti
#define lua_rawgetp lua54_lua_rawgetp
#define lua_rawlen lua54_lua_rawlen
#define lua_rawset lua54_lua_rawset
#define lua_rawseti lua54_lua_rawseti
#define lua_rawsetp lua54_lua_rawsetp
#define lua_resume lua54_lua_resume
#define lua_rotate lua54_lua_rotate
#define lua_setallocf lua54_lua_setallocf
#define lua_setcstacklimit lua54_lua_setcstacklimit
#define lua_setfield lua54_lua_setfield
#define lua_setglobal lua54_lua_setglobal
#define lua_sethook lua54_lua_sethook
#define lua_seti lua54_lua_seti
#define lua_setiuservalue lua54_lua_setiuservalue
#define lua_setlocal lua54_lua_setlocal
#define lua_setmetatable lua54_lua_setmetatable
#define lua_settable lua54_lua_settable
#define lua_settop lua54_lua_settop
#define lua_setupvalue lua54_lua_setupvalue
#define lua_setwarnf lua54_lua_setwarnf
#define lua_status lua54_lua_status
#define lua_stringtonumber lua54_lua_stringtonumber
#define lua_toboolean lua54_lua_toboolean
#define lua_tocfunction lua54_lua_tocfunction
#define lua_toclose lua54_lua_toclose
#define lua_tointegerx lua54_lua_tointegerx
#define lua_tolstring lua54_lua_tolstring
#define lua_tonumberx lua54_lua_tonumberx
#define lua_topointer lua54_lua_topointer
#define lua_tothread lua54_lua_tothread
#define lua_touserdata lua54_lua_touserdata
#define lua_type lua54_lua_type
#define lua_typename lua54_lua_typename
#define lua_upvalueid lua54_lua_upvalueid
#define lua_upvaluejoin lua54_lua_upvaluejoin
#define lua_version lua54_lua_version
#define lua_warning lua54_lua_warning
#define lua_xmove lua54_lua_xmove
#define lua_yieldk lua54_lua_yieldk
#define luaopen_base lua54_luaopen_base
#define luaopen_coroutine lua54_luaopen_coroutine
#define luaopen_debug lua54_luaopen_debug
#define luaopen_io lua54_luaopen_io
#define luaopen_math lua54_luaopen_math
#define luaopen_os lua54_luaopen_os
#define luaopen_package lua54_luaopen_package
#define luaopen_string lua54_luaopen_string
#define luaopen_table lua54_luaopen_table
#define luaopen_utf8 lua54_luaopen_utf8
#define l_likely(x)	luai_likely(x)
#define l_unlikely(x)	luai_unlikely(x)

#include "lua/lua.h"
#include "lua/lauxlib.h"
#include "lua/lualib.h"

#define LUA_FILE_EXTENSION ".pd_lua"

#include "../pdlua.c"
#include "lua/onelua.c"
